stages:
  - update
  - build
  - test
  - push_image

# variables set in your GitLab project's settings
variables:
  DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME  
  DOCKER_HUB_PASSWORD: $DOCKER_HUB_PASSWORD
  IMAGE_NAME: random-num
  TAG: latest 

update-job:
  stage: update
  script:
    - echo "sudo apt update && sudo apt upgrade -y"
    - echo "Update complete."

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME:$TAG .
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:$TAG

lint-test-job:
  stage: test
  script:
    - echo "docker images"
    - sleep 3

push_image:
  stage: push_image
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:$TAG
