---
# - name: install git
#   apt:
#     name: git
#     state: present
#     update_cache: yes

# - name: install sysstat
#   apt:
#     name: sysstat
#     state: present
#     update_cache: yes



# here we use ansible loops


- name: Update the system
  apt:
    update_cache: yes
    upgrade: dist
  tags: 
    - update_system
    - common


- name: Disable swap
  command: swapoff -a
  tags: 
    - disable_swap
    - common


- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  Loop:
    - git
    - sysstat
    - htop
    - atop
    # add any other package names you want to install here.


- name: Remove swap entry from fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#\s]\S*\s+)\S+\s+swap\s+.*$'
    replace: '# \1swap swap'
  notify: Reboot system
  tags: 
    - disable_swap
    - common


