---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  become: true

- name: Add  apt key.
  ansible.builtin.apt_key:
    url: "{{ grafana_apt_gpg_key }}"
    # dest: /etc/apt/trusted.gpg.d/grafana.gpg
    # mode: '0644'
  # register: add_repository_key  
  become: true


- name: Add grafana repository
  ansible.builtin.apt_repository:
    repo: "{{grafana_repo}}"
    state: present
  become: true

- name: Install grafana package
  ansible.builtin.apt:
    pkg: grafana
    state: latest
    update_cache: true
  become: true
- name: Install grafana package
  ansible.builtin.apt:
    pkg: neofetch
    state: absent
    update_cache: true
  become: true
  notify: start grafana service 
