- name: Ensure group node-exporter exists
  ansible.builtin.group:
    name: '{{ group }}'
    state: present
    system: yes
  become: true

- name: add node-exporter user
  user:
    name: '{{ user }}'
    shell: /usr/sbin/nologin
    group: '{{ group }}'
    system: true
  become: true