---
- name: Distribute join command file
  hosts: workers
  become: true
  tasks:
    - name: Copy join command file to worker nodes
      copy:
        src: /path/on/local/machine/kubeadm_join_command.sh
        dest: /root/kubeadm_join_command.sh
        mode: '0755'

    - name: Join worker nodes to the cluster
      shell: /root/kubeadm_join_command.sh