---
- name: ansible-deploy-nfs-server
  hosts: nfs_server
  become: true
...


# sudo apt install nfs-kernel-server
# sudo systemctl start nfs-kernel-server.service
# mkdir /scratch
# /scratch *(rw,async,no_subtree_check,no_root_squash)
# sudo exportfs -a
#
#
#




















