---
- name: Setup entries in resolv.conf file
  hosts: all
  roles:
  - role: "mireiawen.resolvconf"
    dns_nameservers:
    - "1.1.1.1"
    - "8.8.8.8"
    # dns_domain: "localdomain.tld"
    # dns_search_domains:
    # - "localdomain.tld"
    # - "sub.localdomain.tld"
    # - "example.local"
...













