---

- name: changing-dns-servers
  import_playbook: Ansible-Change-Dns.yml


- name: Disabling-swap
  import_playbook: Ansible-Disabling-swap.yml

- name: installing-docker
  import_playbook: Ansible-Install-Docker

...













