---

- name: Update apt cache
  hosts: all
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  hosts: all
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - software-properties-common
    state: present
    update_cache: true
  tags: apt    
...