---

  # Target: where our play will run and options it will run with
  hosts: all
  gather_facts: true



  # Variable: variables that will apply to the play, on all target systems

  vars_files:
    - var_files.yml
    # configuration
    # install_to_host
    # deploy_to_kubernetes


  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Test extra vars
      debug:
        msg: "{{ external_named_list }}"



  # Handlers: handlers that are executed as a notify key from a task




  # Roles: list of roles to be imported into the play



...










- name: Check Ansible version
  hosts: all
  gather_facts: false
  become: no
  run_once: true
  vars:
    minimal_ansible_version: 2.16.4
    maximal_ansible_version: 2.17.0
  tags: always
  tasks:
    - name: "Check {{ minimal_ansible_version }} <= Ansible version < {{ maximal_ansible_version }}"
      assert:
        msg: "Ansible must be between {{ minimal_ansible_version }} and {{ maximal_ansible_version }} exclusive - you have {{ ansible_version.string }}"
        that:
          - ansible_version.string is version(minimal_ansible_version, ">=")
          - ansible_version.string is version(maximal_ansible_version, "<")
      tags:
        - check



- name: Check ansible version
  import_playbook: ansible_version.yml

- name: Gather facts
  import_playbook: facts.yml







