apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-cluster
  labels:
    app: randonm-num
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-num
  template:
    metadata:
      labels:
        app: randonm-num
    spec:
      containers:
        - name: random-num
    image: samankhalife/random-num:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 8569

# kubectl apply -f java-app/deployment
