apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: my-app-
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
commonLabels:
  app: my-app
  environment: dev
patchesStrategicMerge:
  - patch.yaml